package require -exact qsys 15.0
set_module_property NAME relu1_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME relu1_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Cyclone V"}
set_module_assignment hls.cosim.name {\3frelu1@@YAXQEAY1BM@BM@M0@Z}
set_module_assignment hls.compressed.name {relu1}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL relu1_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "windows64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_ecc_pkg.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_pkg.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_mlab_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mlab_fifo.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_enable_sink.v" SYSTEM_VERILOG PATH "ip/acl_enable_sink.v"
add_fileset_file "hld_memory_depth_quantization_pkg.sv" SYSTEM_VERILOG PATH "ip/hld_memory_depth_quantization_pkg.sv"
add_fileset_file "hld_iord.sv" SYSTEM_VERILOG PATH "ip/hld_iord.sv"
add_fileset_file "hld_iord_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_latency.sv"
add_fileset_file "hld_iord_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_valid.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_host.v" SYSTEM_VERILOG PATH "ip/lsu_burst_host.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "hld_iowr.sv" SYSTEM_VERILOG PATH "ip/hld_iowr.sv"
add_fileset_file "hld_iowr_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_latency.sv"
add_fileset_file "hld_iowr_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_valid.sv"
add_fileset_file "hld_loop_profiler.sv" SYSTEM_VERILOG PATH "ip/hld_loop_profiler.sv"
add_fileset_file "hld_sim_latency_tracker.sv" SYSTEM_VERILOG PATH "ip/hld_sim_latency_tracker.sv"
add_fileset_file "acl_loop_limiter.v" SYSTEM_VERILOG PATH "ip/acl_loop_limiter.v"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "relu1_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/relu1_function_wrapper.sv"
add_fileset_file "relu1_function.sv" SYSTEM_VERILOG PATH "ip/relu1_function.sv"
add_fileset_file "relu1_bb_B2_sr_1.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B2_sr_1.sv"
add_fileset_file "relu1_bb_B3_sr_1.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B3_sr_1.sv"
add_fileset_file "relu1_bb_B4_sr_1.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B4_sr_1.sv"
add_fileset_file "relu1_bb_B5_sr_0.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B5_sr_0.sv"
add_fileset_file "relu1_bb_B6_sr_0.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B6_sr_0.sv"
add_fileset_file "relu1_bb_B7_sr_0.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B7_sr_0.sv"
add_fileset_file "relu1_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B0_runOnce.sv"
add_fileset_file "relu1_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B0_runOnce_stall_region.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "relu1_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B0_runOnce_merge_reg.sv"
add_fileset_file "relu1_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B0_runOnce_branch.sv"
add_fileset_file "relu1_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B0_runOnce_merge.sv"
add_fileset_file "relu1_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B1_start.sv"
add_fileset_file "relu1_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B1_start_stall_region.sv"
add_fileset_file "relu1_i_iord_bl_call_unnamed_relu12_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_iord_bl_call_unnamed_relu12_relu10.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_wt_entry_s_c0_enter9_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_wt_entry_s_c0_enter9_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_relu10.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going22_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going22_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond23_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond23_0.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_3_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_3_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_4_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_4_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"
add_fileset_file "relu1_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B1_start_merge_reg.sv"
add_fileset_file "relu1_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B1_start_branch.sv"
add_fileset_file "relu1_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B1_start_merge.sv"
add_fileset_file "relu1_bb_B2.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B2.sv"
add_fileset_file "relu1_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B2_stall_region.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_for_cond1_preheader_s_c0_enter6710_relu11.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_for_cond1_preheader_s_c0_enter6710_relu11.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit69_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit69_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t69_relu11_data_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t69_relu11_data_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000relu11_full_detector.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000relu11_full_detector.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_for_cond1_preh0000_c0_enter6710_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_for_cond1_preh0000_c0_enter6710_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going18_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going18_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop11_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop11_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i4_fpga_indvars_iv6_pop10_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i4_fpga_indvars_iv6_pop10_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond19_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond19_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_push11_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_push11_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i4_fpga_indvars_iv6_push10_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i4_fpga_indvars_iv6_push10_0.sv"
add_fileset_file "relu1_B2_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B2_merge_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_3_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_3_reg.sv"
add_fileset_file "relu1_B2_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B2_branch.sv"
add_fileset_file "relu1_B2_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B2_merge.sv"
add_fileset_file "relu1_bb_B3.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B3.sv"
add_fileset_file "relu1_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B3_stall_region.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_for_cond4_preheader_s_c0_enter7211_relu11.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_for_cond4_preheader_s_c0_enter7211_relu11.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit78_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit78_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t78_relu11_data_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t78_relu11_data_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0001relu11_full_detector.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0001relu11_full_detector.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_for_cond4_preh0000_c0_enter7211_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_for_cond4_preh0000_c0_enter7211_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going13_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going13_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond827_pop16_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond827_pop16_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1233_pop19_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1233_pop19_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1629_pop17_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1629_pop17_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_i_018_pop14_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_i_018_pop14_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop1131_pop18_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop1131_pop18_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv3_pop13_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv3_pop13_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond827_push16_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond827_push16_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1233_push19_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1233_push19_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1629_push17_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1629_push17_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond14_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond14_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_i_018_push14_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_i_018_push14_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_pop1131_push18_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_pop1131_push18_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i6_fpga_indvars_iv3_push13_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i6_fpga_indvars_iv3_push13_0.sv"
add_fileset_file "relu1_B3_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B3_merge_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_3_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_3_reg.sv"
add_fileset_file "relu1_B3_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B3_branch.sv"
add_fileset_file "relu1_B3_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B3_merge.sv"
add_fileset_file "relu1_bb_B4.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B4.sv"
add_fileset_file "relu1_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B4_stall_region.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_for_body6_s_c0_enter8412_relu151.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_for_body6_s_c0_enter8412_relu151.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_body6_s_c0_exit87_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_body6_s_c0_exit87_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t87_relu11_data_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t87_relu11_data_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0002relu11_full_detector.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0002relu11_full_detector.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_for_body6_s_c0_enter8412_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_for_body6_s_c0_enter8412_relu10.sv"
add_fileset_file "relu1_B4_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B4_merge_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_in0209_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_in0209_0.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_out02110_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_out02110_0.sv"
add_fileset_file "relu1_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "relu1_i_llvm_fpga_mem_unnamed_5_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_mem_unnamed_5_relu10.sv"
add_fileset_file "relu1_readdata_reg_unnamed_5_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_readdata_reg_unnamed_5_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going_3_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going_3_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_8_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_8_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_12_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_12_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_11_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_11_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_15_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_15_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_6_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_6_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_9_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_9_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_13_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_13_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_cleanups_pop24_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_cleanups_pop24_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_cleanups_pop24_2_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_cleanups_pop24_2_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_initerations_pop23_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_initerations_pop23_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_initerations_pop23_4_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_initerations_pop23_4_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_10_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_10_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_j_017_pop21_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_j_017_pop21_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_j_017_pop21_5_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_j_017_pop21_5_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_14_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_14_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_7_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_7_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond535_push29_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond535_push29_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond535_push29_24_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond535_push29_24_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond828_push25_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond828_push25_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond828_push25_29_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond828_push25_29_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_lastiniteration_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_lastiniteration_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_lastiniteration_45_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_lastiniteration_45_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_28_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_28_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_33_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_33_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi_push22_55_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi_push22_55_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1136_push30_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1136_push30_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1136_push30_25_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1136_push30_25_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1630_push26_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1630_push26_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1630_push26_30_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1630_push26_30_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond_40_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond_40_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_cleanups_push24_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_cleanups_push24_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_cleanups_push24_53_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_cleanups_push24_53_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_initerations_push23_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_initerations_push23_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_initerations_push23_36_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_initerations_push23_36_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_26_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_26_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_j_017_push21_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_j_017_push21_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_j_017_push21_38_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_j_017_push21_38_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_31_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_31_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_41_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_41_reg.sv"
add_fileset_file "relu1_B4_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B4_branch.sv"
add_fileset_file "relu1_B4_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B4_merge.sv"
add_fileset_file "relu1_bb_B5.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B5.sv"
add_fileset_file "relu1_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B5_stall_region.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0_reg.sv"
add_fileset_file "relu1_B5_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B5_branch.sv"
add_fileset_file "relu1_B5_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B5_merge.sv"
add_fileset_file "relu1_bb_B6.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B6.sv"
add_fileset_file "relu1_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B6_stall_region.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0_reg.sv"
add_fileset_file "relu1_B6_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B6_branch.sv"
add_fileset_file "relu1_B6_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B6_merge.sv"
add_fileset_file "relu1_bb_B7.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B7.sv"
add_fileset_file "relu1_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B7_stall_region.sv"
add_fileset_file "relu1_i_iowr_bl_return_unnamed_relu16_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_iowr_bl_return_unnamed_relu16_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv"
add_fileset_file "relu1_B7_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B7_branch.sv"
add_fileset_file "relu1_B7_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B7_merge.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going13_2_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going13_2_sr.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going13_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going13_2_valid_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going18_2_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going18_2_sr.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going18_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going18_2_valid_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going22_1_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going22_1_sr.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going22_1_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going22_1_valid_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going_3_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going_3_sr.sv"
add_fileset_file "relu1_loop_limiter_0.sv" SYSTEM_VERILOG PATH "ip/relu1_loop_limiter_0.sv"
add_fileset_file "relu1_loop_limiter_1.sv" SYSTEM_VERILOG PATH "ip/relu1_loop_limiter_1.sv"
add_fileset_file "relu1_loop_limiter_2.sv" SYSTEM_VERILOG PATH "ip/relu1_loop_limiter_2.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_host_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_host_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_agent_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_agent_endpoint.v"
add_fileset_file "acl_ic_agent_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_agent_rrp.v"
add_fileset_file "acl_ic_agent_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_agent_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "relu1_internal.v" SYSTEM_VERILOG PATH "relu1_internal.v"

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL relu1_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "windows64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_ecc_pkg.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_pkg.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_mlab_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mlab_fifo.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_enable_sink.v" SYSTEM_VERILOG PATH "ip/acl_enable_sink.v"
add_fileset_file "hld_memory_depth_quantization_pkg.sv" SYSTEM_VERILOG PATH "ip/hld_memory_depth_quantization_pkg.sv"
add_fileset_file "hld_iord.sv" SYSTEM_VERILOG PATH "ip/hld_iord.sv"
add_fileset_file "hld_iord_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_latency.sv"
add_fileset_file "hld_iord_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_valid.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_host.v" SYSTEM_VERILOG PATH "ip/lsu_burst_host.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "hld_iowr.sv" SYSTEM_VERILOG PATH "ip/hld_iowr.sv"
add_fileset_file "hld_iowr_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_latency.sv"
add_fileset_file "hld_iowr_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_valid.sv"
add_fileset_file "hld_loop_profiler.sv" SYSTEM_VERILOG PATH "ip/hld_loop_profiler.sv"
add_fileset_file "hld_sim_latency_tracker.sv" SYSTEM_VERILOG PATH "ip/hld_sim_latency_tracker.sv"
add_fileset_file "acl_loop_limiter.v" SYSTEM_VERILOG PATH "ip/acl_loop_limiter.v"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "relu1_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/relu1_function_wrapper.sv"
add_fileset_file "relu1_function.sv" SYSTEM_VERILOG PATH "ip/relu1_function.sv"
add_fileset_file "relu1_bb_B2_sr_1.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B2_sr_1.sv"
add_fileset_file "relu1_bb_B3_sr_1.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B3_sr_1.sv"
add_fileset_file "relu1_bb_B4_sr_1.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B4_sr_1.sv"
add_fileset_file "relu1_bb_B5_sr_0.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B5_sr_0.sv"
add_fileset_file "relu1_bb_B6_sr_0.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B6_sr_0.sv"
add_fileset_file "relu1_bb_B7_sr_0.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B7_sr_0.sv"
add_fileset_file "relu1_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B0_runOnce.sv"
add_fileset_file "relu1_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B0_runOnce_stall_region.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "relu1_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B0_runOnce_merge_reg.sv"
add_fileset_file "relu1_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B0_runOnce_branch.sv"
add_fileset_file "relu1_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B0_runOnce_merge.sv"
add_fileset_file "relu1_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B1_start.sv"
add_fileset_file "relu1_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B1_start_stall_region.sv"
add_fileset_file "relu1_i_iord_bl_call_unnamed_relu12_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_iord_bl_call_unnamed_relu12_relu10.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_wt_entry_s_c0_enter9_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_wt_entry_s_c0_enter9_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_relu10.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter9_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going22_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going22_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond23_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond23_0.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_3_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_3_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_4_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_source_p1024a28a28f32_unnamed_4_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"
add_fileset_file "relu1_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B1_start_merge_reg.sv"
add_fileset_file "relu1_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B1_start_branch.sv"
add_fileset_file "relu1_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B1_start_merge.sv"
add_fileset_file "relu1_bb_B2.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B2.sv"
add_fileset_file "relu1_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B2_stall_region.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_for_cond1_preheader_s_c0_enter6710_relu11.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_for_cond1_preheader_s_c0_enter6710_relu11.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit69_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit69_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t69_relu11_data_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t69_relu11_data_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000relu11_full_detector.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000relu11_full_detector.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_for_cond1_preh0000_c0_enter6710_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_for_cond1_preh0000_c0_enter6710_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going18_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going18_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop11_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop11_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i4_fpga_indvars_iv6_pop10_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i4_fpga_indvars_iv6_pop10_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond19_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond19_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_push11_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_push11_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i4_fpga_indvars_iv6_push10_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i4_fpga_indvars_iv6_push10_0.sv"
add_fileset_file "relu1_B2_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B2_merge_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_3_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop12_3_reg.sv"
add_fileset_file "relu1_B2_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B2_branch.sv"
add_fileset_file "relu1_B2_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B2_merge.sv"
add_fileset_file "relu1_bb_B3.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B3.sv"
add_fileset_file "relu1_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B3_stall_region.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_for_cond4_preheader_s_c0_enter7211_relu11.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_for_cond4_preheader_s_c0_enter7211_relu11.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit78_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000r_s_c0_exit78_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t78_relu11_data_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t78_relu11_data_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0001relu11_full_detector.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0001relu11_full_detector.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_for_cond4_preh0000_c0_enter7211_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_for_cond4_preh0000_c0_enter7211_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going13_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going13_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond827_pop16_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond827_pop16_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1233_pop19_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1233_pop19_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1629_pop17_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1629_pop17_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_i_018_pop14_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_i_018_pop14_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop1131_pop18_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop1131_pop18_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv3_pop13_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv3_pop13_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond827_push16_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond827_push16_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1233_push19_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1233_push19_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1629_push17_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1629_push17_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond14_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond14_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_i_018_push14_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_i_018_push14_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_pop1131_push18_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_pop1131_push18_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i6_fpga_indvars_iv3_push13_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i6_fpga_indvars_iv3_push13_0.sv"
add_fileset_file "relu1_B3_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B3_merge_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_3_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop15_3_reg.sv"
add_fileset_file "relu1_B3_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B3_branch.sv"
add_fileset_file "relu1_B3_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B3_merge.sv"
add_fileset_file "relu1_bb_B4.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B4.sv"
add_fileset_file "relu1_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B4_stall_region.sv"
add_fileset_file "relu1_i_sfc_s_c0_in_for_body6_s_c0_enter8412_relu151.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_s_c0_in_for_body6_s_c0_enter8412_relu151.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_body6_s_c0_exit87_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_body6_s_c0_exit87_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t87_relu11_data_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0000t87_relu11_data_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0002relu11_full_detector.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_sfc_exit_s_c0_out_for_0002relu11_full_detector.sv"
add_fileset_file "relu1_i_sfc_logic_s_c0_in_for_body6_s_c0_enter8412_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_sfc_logic_s_c0_in_for_body6_s_c0_enter8412_relu10.sv"
add_fileset_file "relu1_B4_merge_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_B4_merge_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_in0209_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_in0209_0.sv"
add_fileset_file "relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_out02110_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_ffwd_dest_p1024a28a28f32_out02110_0.sv"
add_fileset_file "relu1_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "relu1_i_llvm_fpga_mem_unnamed_5_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_mem_unnamed_5_relu10.sv"
add_fileset_file "relu1_readdata_reg_unnamed_5_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_readdata_reg_unnamed_5_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going_3_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going_3_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_8_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond535_pop29_8_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_12_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_exitcond828_pop25_12_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_11_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi1_pop1538_pop32_11_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_15_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi2_pop1234_pop28_15_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_6_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_memdep_phi_pop22_6_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_9_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1136_pop30_9_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_13_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i1_notcmp1630_pop26_13_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_cleanups_pop24_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_cleanups_pop24_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_cleanups_pop24_2_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_cleanups_pop24_2_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_initerations_pop23_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_initerations_pop23_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i2_initerations_pop23_4_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i2_initerations_pop23_4_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_10_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_i_018_pop1437_pop31_10_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_j_017_pop21_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_j_017_pop21_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_j_017_pop21_5_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_j_017_pop21_5_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_14_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i32_k_019_pop1132_pop27_14_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_0.sv"
add_fileset_file "relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_7_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pop_i6_fpga_indvars_iv_pop20_7_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond535_push29_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond535_push29_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond535_push29_24_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond535_push29_24_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond828_push25_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond828_push25_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_exitcond828_push25_29_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_exitcond828_push25_29_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_lastiniteration_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_lastiniteration_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_lastiniteration_45_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_lastiniteration_45_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_28_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_pop1538_push32_28_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_33_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_pop1234_push28_33_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi_push22_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi_push22_55_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi_push22_55_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1136_push30_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1136_push30_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1136_push30_25_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1136_push30_25_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1630_push26_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1630_push26_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notcmp1630_push26_30_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notcmp1630_push26_30_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_notexitcond_40_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_notexitcond_40_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_cleanups_push24_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_cleanups_push24_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_cleanups_push24_53_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_cleanups_push24_53_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_initerations_push23_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_initerations_push23_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i2_initerations_push23_36_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i2_initerations_push23_36_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_26_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_i_018_pop1437_push31_26_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_j_017_push21_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_j_017_push21_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_j_017_push21_38_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_j_017_push21_38_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_31_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i32_k_019_pop1132_push27_31_reg.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_41_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i6_fpga_indvars_iv_push20_41_reg.sv"
add_fileset_file "relu1_B4_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B4_branch.sv"
add_fileset_file "relu1_B4_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B4_merge.sv"
add_fileset_file "relu1_bb_B5.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B5.sv"
add_fileset_file "relu1_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B5_stall_region.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi1_push15_0_reg.sv"
add_fileset_file "relu1_B5_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B5_branch.sv"
add_fileset_file "relu1_B5_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B5_merge.sv"
add_fileset_file "relu1_bb_B6.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B6.sv"
add_fileset_file "relu1_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B6_stall_region.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_i1_memdep_phi2_push12_0_reg.sv"
add_fileset_file "relu1_B6_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B6_branch.sv"
add_fileset_file "relu1_B6_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B6_merge.sv"
add_fileset_file "relu1_bb_B7.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B7.sv"
add_fileset_file "relu1_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/relu1_bb_B7_stall_region.sv"
add_fileset_file "relu1_i_iowr_bl_return_unnamed_relu16_relu10.sv" SYSTEM_VERILOG PATH "ip/relu1_i_iowr_bl_return_unnamed_relu16_relu10.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "relu1_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv"
add_fileset_file "relu1_B7_branch.sv" SYSTEM_VERILOG PATH "ip/relu1_B7_branch.sv"
add_fileset_file "relu1_B7_merge.sv" SYSTEM_VERILOG PATH "ip/relu1_B7_merge.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going13_2_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going13_2_sr.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going13_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going13_2_valid_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going18_2_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going18_2_sr.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going18_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going18_2_valid_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going22_1_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going22_1_sr.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going22_1_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going22_1_valid_fifo.sv"
add_fileset_file "relu1_i_llvm_fpga_pipeline_keep_going_3_sr.sv" SYSTEM_VERILOG PATH "ip/relu1_i_llvm_fpga_pipeline_keep_going_3_sr.sv"
add_fileset_file "relu1_loop_limiter_0.sv" SYSTEM_VERILOG PATH "ip/relu1_loop_limiter_0.sv"
add_fileset_file "relu1_loop_limiter_1.sv" SYSTEM_VERILOG PATH "ip/relu1_loop_limiter_1.sv"
add_fileset_file "relu1_loop_limiter_2.sv" SYSTEM_VERILOG PATH "ip/relu1_loop_limiter_2.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_host_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_host_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_agent_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_agent_endpoint.v"
add_fileset_file "acl_ic_agent_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_agent_rrp.v"
add_fileset_file "acl_ic_agent_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_agent_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "relu1_internal.v" SYSTEM_VERILOG PATH "relu1_internal.v"

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### Parameter in0 interface
add_interface in0 conduit sink
set_interface_property in0 associatedClock clock
set_interface_property in0 associatedReset reset
set_interface_assignment in0 hls.cosim.name {in}
add_interface_port in0 in0 data input 64

#### Parameter out0 interface
add_interface out0 conduit sink
set_interface_property out0 associatedClock clock
set_interface_property out0 associatedReset reset
set_interface_assignment out0 hls.cosim.name {out}
add_interface_port out0 out0 data input 64

#### Host interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
